### ISSUE TITLE
error fetching OTP API.

### ISSUE THREAD

**Issue by nolimits0007** [bombardier-gif/covid-vaccine-booking#406] opened 2021-05-30 11:16 UTC
There is an error saying error fetching OTP API.

<img width="925" alt="Screenshot 2021-05-30 at 16 42 47" src="https://user-images.githubusercontent.com/84738436/120101971-80ffba00-c166-11eb-809a-0c836c77d3d0.png">

**Comment by darthfishious** [comment] 2021-05-30 11:16
same issue

**Comment by sanketpandia** [comment] 2021-05-30 11:23
It is a kvdb issue. The buckets seemed to be missing

**Comment by nolimits0007** [comment] 2021-05-30 11:23
> same issue.
> 
> is this a kvdb issue? it works fine with manual OTP input.
> 
> the apk and IFTTT both are failing to send the OTP to kvdb.

Might be an issue with kvdb

**Comment by kunalmoharir** [comment] 2021-05-30 11:29
I guess the kvdb 14 day free trial is over.

**Comment by nolimits0007** [comment] 2021-05-30 11:30
> I guess the kvdb 14 day free trial is over.

Then what to do.

**Comment by kunalmoharir** [comment] 2021-05-30 11:33
We can create our own account for another 14 days and then 
modify the this url https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/99XXXXXXXX 
Change it to the new one in the ifttt.com to point the one we created.

**Comment by nijeesh4all** [comment] 2021-05-30 11:35
duplicate #405

**Comment by sync-1203** [comment] 2021-05-30 11:37
> We can create our own account for another 14 days and then
> modify the this url https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/99XXXXXXXX
> Change it to the new one in the ifttt.com to point the one we created.

Tested and working? can anyone confirm if this is the issue and fix?

**Comment by darthfishious** [comment] 2021-05-30 11:42
rather than each one create their own individual account, can we rather create another common free trial account for the next 14 day and update the apk with the new bucket details and readme for IFTTT?

**Comment by kunalmoharir** [comment] 2021-05-30 11:47
Creating bucket doesn't require to create account. 
You can do that directly. I am trying that out now

**Comment by rishirawal** [comment] 2021-05-30 11:49
let us know if you succeed

**Comment by parthvshah** [comment] 2021-05-30 11:55
You need to change the secret key as part of the clear_bucket_and_send_OTP function.

**Comment by nolimits0007** [comment] 2021-05-30 11:57
> You need to change the secret key as part of the clear_bucket_and_send_OTP function.

What will be the secret Key can u tell.

**Comment by kunalmoharir** [comment] 2021-05-30 11:59
It works, I created by own bucket and replaced the bucket name with the one i created. 
utils.py line no. 1042

**Comment by darthfishious** [comment] 2021-05-30 12:01
how do we make changes in the apk file?

**Comment by nolimits0007** [comment] 2021-05-30 12:02
> It works, I created my own bucket and replaced the bucket name with the one i created.
> utils.py line no. 1042

PLz merge it in the main code

**Comment by naidusuresh36** [comment] 2021-05-30 12:03
> 
> 
> It works, I created my own bucket and replaced the bucket name with the one i created.
> utils.py line no. 1042

Can you please explain step-wise? 

I am a noob.

**Comment by nolimits0007** [comment] 2021-05-30 12:06
> > It works, I created my own bucket and replaced the bucket name with the one i created.
> > utils.py line no. 1042
> 
> PLz merge it in the main code

Can u plz share the bucket key so that i can also change in my utils.py

**Comment by rooniks** [comment] 2021-05-30 12:06
Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
Steps to make it working again:
- Go to https://kvdb.io/
- Click on `Get started now`
- Enter your email and click on `Create bucket`
- You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get. 
- Restart the script.

**Comment by naidusuresh36** [comment] 2021-05-30 12:10
> 
> 
> Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> Steps to make it working again:
> 
>     * Go to https://kvdb.io/
> 
>     * Click on `Get started now`
> 
>     * Enter your email and click on `Create bucket`
> 
>     * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> 
>     * Restart the script.

How to change the value in the python script?

**Comment by ernitish** [comment] 2021-05-30 12:12
> Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> Steps to make it working again:
> 
> * Go to https://kvdb.io/
> * Click on `Get started now`
> * Enter your email and click on `Create bucket`
> * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> * Restart the script.

How to change KVDB bucket in cowin OTP retriever app??
any suggestion?

**Comment by nolimits0007** [comment] 2021-05-30 12:12
> Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> Steps to make it working again:
> 
> * Go to https://kvdb.io/
> * Click on `Get started now`
> * Enter your email and click on `Create bucket`
> * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> * Restart the script.

Why to use million buckets why not single . we have to take care of others also. why not merge this  thing to main.

**Comment by rooniks** [comment] 2021-05-30 12:12
> > Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> > Steps to make it working again:
> > ```
> > * Go to https://kvdb.io/
> > 
> > * Click on `Get started now`
> > 
> > * Enter your email and click on `Create bucket`
> > 
> > * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> > 
> > * Restart the script.
> > ```
> 
> How to change the value in the python script?

Open the script in any text editor. If you're on Windows, Notepad should be good enough. Find and replace ASth4wnvVDPkg2bdjsiqMN with your own bucket value.

**Comment by rooniks** [comment] 2021-05-30 12:14
> > Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> > Steps to make it working again:
> > 
> > * Go to https://kvdb.io/
> > * Click on `Get started now`
> > * Enter your email and click on `Create bucket`
> > * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> > * Restart the script.
> 
> Why to use million buckets why not single . we have to take care of others also. why not merge this thing to main.

Agreed. But then typically, this is a secret value and they shouldn't be shared. Also, it would create the same problem again after 14 days. Unless we have someone sponsoring a paid account, adding a trial key the main branch would keep repeating the same issue again and again. Better to instruct in ReadMe on how to create your own key value and accept that key value in the prompts like we had anti-captcha key initially.

**Comment by kunalmoharir** [comment] 2021-05-30 12:14
> > Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> > Steps to make it working again:
> > 
> > * Go to https://kvdb.io/
> > * Click on `Get started now`
> > * Enter your email and click on `Create bucket`
> > * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> > * Restart the script.
> 
> How to change KVDB bucket in cowin OTP retriever app??
> any suggestion?

Search for file : - covid-vaccine-booking-main\src\CoWinOTPRetriever\app\src\main\res\values\string.xml 
Replace <string name="kvdb_default_key">ASth4wnvVDPkg2bdjsiqMN</string> with your bucket name at line 7

**Comment by rishirawal** [comment] 2021-05-30 12:14
so will old secret key work?

**Comment by kunalmoharir** [comment] 2021-05-30 12:15
> so will old secret key work?

Not unless the repo owner gets the paid version, which is unlikely.

**Comment by great1113** [comment] 2021-05-30 12:17
@rishirawal  By secret key if you mean "ASth4wnvVDPkg2bdjsiqMN " (which is the Bucket value), then no it won't work.


Yeah nobody is going to pay 19$ a month for kvdb premium and that too give it away for others for free.

**Comment by nijeesh4all** [comment] 2021-05-30 12:17
>so will old secret key work?

i dont think the cowin sms retriever will not work for now, use IFTT instead.  

https://github.com/bombardier-gif/covid-vaccine-booking#option-1-ifttt

**Comment by darthfishious** [comment] 2021-05-30 12:17
> > > Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> > > Steps to make it working again:
> > > 
> > > * Go to https://kvdb.io/
> > > * Click on `Get started now`
> > > * Enter your email and click on `Create bucket`
> > > * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> > > * Restart the script.
> > 
> > 
> > How to change KVDB bucket in cowin OTP retriever app??
> > any suggestion?
> 
> Search for file : - covid-vaccine-booking-main\src\CoWinOTPRetriever\app\src\main\res\values\string.xml
> Replace ASth4wnvVDPkg2bdjsiqMN with your bucket name at line 7

the bucket name can be changed within the app itself.

**Comment by great1113** [comment] 2021-05-30 12:19
Yeah, when in the stopped state the Bucket value is editable inside the Android App.

**Comment by great1113** [comment] 2021-05-30 12:20
I had to make my own version of the app and script (slight changes only) to make it work with thisdb.com

**Comment by kunalmoharir** [comment] 2021-05-30 12:21
Should not be that hard to do , it is just find and replace of the bucket name .

**Comment by great1113** [comment] 2021-05-30 12:22
We could add the bucket value as an argument or part of the input process to the script at run time to make it easier for people instead of asking for them to make changes in the script files.

**Comment by ernitish** [comment] 2021-05-30 12:25
> Yeah, when in the stopped state the Bucket value is editable inside the Android App.

cool

**Comment by rooniks** [comment] 2021-05-30 12:28
> We could add the bucket value as an argument or part of the input process to the script at run time to make it easier for people instead of asking for them to make changes in the script files.

Yes. Instructing to create a kvdb bucket should be part of the ReadMe and the bucket value should be accepted via standard input.

**Comment by amitcodin** [comment] 2021-05-30 12:39
The new bucket that we create on kvdb. That page should be open all the time or are you hosting that on a server or logging in with emails to keep it saved?

**Comment by sync-1203** [comment] 2021-05-30 12:42
Now this!

![image](https://user-images.githubusercontent.com/84703153/120104535-7e0ac680-c172-11eb-99ae-e7c9a76be543.png)

**Comment by darthfishious** [comment] 2021-05-30 12:42
please create a single bucket. there is extreme load on the server and it is unable to clear bucket and retrieve otp half the time.

**Comment by sync-1203** [comment] 2021-05-30 12:43
> please create a single bucket. there is extreme load on the server and it is unable to clear bucket and retrieve otp half the time.

Yeah - I have created my own bucket. But still get this on the listener app.

**Comment by kunalmoharir** [comment] 2021-05-30 12:44
> Now this!
> 
> ![image](https://user-images.githubusercontent.com/84703153/120104535-7e0ac680-c172-11eb-99ae-e7c9a76be543.png)

I didn't get this, could you share your bucket id if possible ?

**Comment by sync-1203** [comment] 2021-05-30 12:46
R1dqbh15GfkNNGNoetgYYj


> > Now this!
> > ![image](https://user-images.githubusercontent.com/84703153/120104535-7e0ac680-c172-11eb-99ae-e7c9a76be543.png)
> 
> I didn't get this, could you share your bucket id if possible ?

**Comment by shachiii** [comment] 2021-05-30 12:46
> > Now this!
> > ![image](https://user-images.githubusercontent.com/84703153/120104535-7e0ac680-c172-11eb-99ae-e7c9a76be543.png)
> 
> I didn't get this, could you share your bucket id if possible ?

I'm facing the same issue with bucket id 2Pfb9d87vgUwjpH3okmemW

**Comment by thewebcapsule** [comment] 2021-05-30 12:47
I think kvdb.io is down.

**Comment by tilakv95** [comment] 2021-05-30 12:47
I have created a new bucket ID and replaced it on both the app and the script. Still get the below error. Does anyone have any idea?
![image](https://user-images.githubusercontent.com/14173642/120104677-46504e80-c173-11eb-92b0-6025474c80c8.png)

**Comment by amitcodin** [comment] 2021-05-30 12:50
Looks like everyone creating their own buckets is hanging the server for all. Rather use one common bucket for everyone so it is atleast fast enough and won't go down

**Comment by toshthakkar** [comment] 2021-05-30 12:54
> Now this!
> 
> ![image](https://user-images.githubusercontent.com/84703153/120104535-7e0ac680-c172-11eb-99ae-e7c9a76be543.png)

even I got this despite of creating new bucket.

**Comment by shachiii** [comment] 2021-05-30 12:54
How do we settle on one bucket key?

**Comment by thewebcapsule** [comment] 2021-05-30 12:54
@shachiii Using the one specified by the dev of the app.

**Comment by sanketpandia** [comment] 2021-05-30 12:56
> Looks like everyone creating their own buckets is hanging the server for all. Rather use one common bucket for everyone so it is atleast fast enough and won't go down

"Server is down" is a generic error message that the author has added by himself. Its not an error response from kvdb. I don't think its because of the heavy load. Something else is the issue

**Comment by shachiii** [comment] 2021-05-30 12:59
> @shachiii Using the one specified by the dev of the app.

I don't think that one is working

**Comment by sync-1203** [comment] 2021-05-30 12:59
Its fixed now....working for me.

**Comment by rishirawal** [comment] 2021-05-30 13:00
I am using ifttt aplet.. and seems to be timeing out while reaching kvdb. Responsetime sucks.. dont know if this is generic kvdb issue or we need a common bucket

**Comment by nijeesh4all** [comment] 2021-05-30 13:00
i think instead of waiting for someone to create a new free bucket and use it, and waiting for it to expire after another 14 days we should start looking for some other alternatives 

```
from http.server import HTTPServer, BaseHTTPRequestHandler

from io import BytesIO

class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    message = ''

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(SimpleHTTPRequestHandler.message.encode())

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length).decode('utf-8')
        self.send_response(200)
        self.end_headers()
        response = BytesIO()
        SimpleHTTPRequestHandler.message = body
        self.wfile.write(SimpleHTTPRequestHandler.message.encode())


httpd = HTTPServer(('localhost', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()
```

**Comment by darthfishious** [comment] 2021-05-30 13:01
> Its fixed now....working for me.

it works only intermittently. and as @rishirawal mentioned, the response time is terrible whenever it works.

**Comment by nijeesh4all** [comment] 2021-05-30 13:06
i think instead of waiting for someone to create a new free bucket and use it, and waiting for it to expire after another 14 days we should start looking for someother alternatives 

i am running my code in an AWS ec2 instance. so i ran this code on screen.
added the firewall rules

then i just replaced the kvdb url with my severs public ip.

after setting the IFTT up, voila it started working again. 


if you are not running on a server but on a local machine, try running `ngrok` and use its url in place of the server's pulic ip


```
from http.server import HTTPServer, BaseHTTPRequestHandler

from io import BytesIO

class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    message = ''

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(SimpleHTTPRequestHandler.message.encode())

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length).decode('utf-8')
        self.send_response(200)
        self.end_headers()
        response = BytesIO()
        SimpleHTTPRequestHandler.message = body
        self.wfile.write(SimpleHTTPRequestHandler.message.encode())


httpd = HTTPServer(('localhost', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()
```

i dont know if this is the best solution, but it works

**Comment by thewebcapsule** [comment] 2021-05-30 13:07
@nijeesh4all Can you share your public IP :P

I have a spare VPS you can use.

**Comment by pics12456** [comment] 2021-05-30 13:08
> > > Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> > > Steps to make it working again:
> > > 
> > > * Go to https://kvdb.io/
> > > * Click on `Get started now`
> > > * Enter your email and click on `Create bucket`
> > > * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> > > * Restart the script.
> > 
> > 
> > How to change KVDB bucket in cowin OTP retriever app??
> > any suggestion?
> 
> Search for file : - covid-vaccine-booking-main\src\CoWinOTPRetriever\app\src\main\res\values\string.xml
> Replace ASth4wnvVDPkg2bdjsiqMN with your bucket name at line 7

I am using covid-vaccine-slot-booking.exe
This is a standalone exe file

How to change the Kvdb bucket id in this?

I have changed the bucket id in the src path mentioned above
But how to change it in the exe file?

**Comment by nijeesh4all** [comment] 2021-05-30 13:10
> @nijeesh4all Can you share your public IP :P

i am thinking about hosting a key-value store there, with the current implementation it only stores just one last message. so it cannot be used by multiple users.

you can either set up and AWS-free tire account for 0$ ( you will get an free instance then )
or you can run an http proxy like ngrok on your local-machine

**Comment by kunalmoharir** [comment] 2021-05-30 13:10
> > > > Confirmed, it's a kvdb issue. Most probably, the free trial has expired for the bucket: `ASth4wnvVDPkg2bdjsiqMN`
> > > > Steps to make it working again:
> > > > 
> > > > * Go to https://kvdb.io/
> > > > * Click on `Get started now`
> > > > * Enter your email and click on `Create bucket`
> > > > * You will get your own bucket key. Replace `ASth4wnvVDPkg2bdjsiqMN` in the script with the value you get.
> > > > * Restart the script.
> > > 
> > > 
> > > How to change KVDB bucket in cowin OTP retriever app??
> > > any suggestion?
> > 
> > 
> > Search for file : - covid-vaccine-booking-main\src\CoWinOTPRetriever\app\src\main\res\values\string.xml
> > Replace ASth4wnvVDPkg2bdjsiqMN with your bucket name at line 7
> 
> I am using covid-vaccine-slot-booking.exe
> This is a standalone exe file
> 
> How to change the Kvdb bucket id in this?
> 
> I have changed the bucket id in the src path mentioned above
> But how to change it in the exe file?

The exe is built using the code, so if any changes to the code then you will have to rebuild the exe. 
The alternative is to enter otp manually, that is working properly . No issues when using exe with manual otp.

**Comment by pics12456** [comment] 2021-05-30 13:11
How to rebuild the exe?

**Comment by kunalmoharir** [comment] 2021-05-30 13:12
> How to rebuild the exe?

https://datatofish.com/executable-pyinstaller/
check this.

**Comment by thewebcapsule** [comment] 2021-05-30 13:13
I need to share the app with 2 old people at the moment so I'm not sure the local idea would be the best in my case. Let me know once your implementation succeeds. Eagerly waiting!

**Comment by MananManek** [comment] 2021-05-30 13:20
> > How to rebuild the exe?
> 
> https://datatofish.com/executable-pyinstaller/
> check this.

I'm not a coder, don't quite understand this, it'll be great if we could get a step by step guide how to edit the exe

**Comment by thewebcapsule** [comment] 2021-05-30 13:26
@bombardier-gif Bhai desh bachalo

**Comment by toshthakkar** [comment] 2021-05-30 13:37
> i think instead of waiting for someone to create a new free bucket and use it, and waiting for it to expire after another 14 days we should start looking for someother alternatives
> 
> i am running my code in an AWS ec2 instance. so i ran this code on screen.
> added the firewall rules
> 
> then i just replaced the kvdb url with my severs public ip.
> 
> after setting the IFTT up, voila it started working again.
> 
> if you are not running on a server but on a local machine, try running `ngrok` and use its url in place of the server's pulic ip
> 
> ```
> from http.server import HTTPServer, BaseHTTPRequestHandler
> 
> from io import BytesIO
> 
> class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
>     message = ''
> 
>     def do_GET(self):
>         self.send_response(200)
>         self.end_headers()
>         self.wfile.write(SimpleHTTPRequestHandler.message.encode())
> 
>     def do_POST(self):
>         content_length = int(self.headers['Content-Length'])
>         body = self.rfile.read(content_length).decode('utf-8')
>         self.send_response(200)
>         self.end_headers()
>         response = BytesIO()
>         SimpleHTTPRequestHandler.message = body
>         self.wfile.write(SimpleHTTPRequestHandler.message.encode())
> 
> 
> httpd = HTTPServer(('localhost', 8000), SimpleHTTPRequestHandler)
> httpd.serve_forever()
> ```
> 
> i dont know if this is the best solution, but it works.
> 
> one caveat though, if you are using ngrok then it will be only available for a 24hours, then the url will change, so yu have to change your server url in IFTT

@nijeesh4all can you elaborate how to setup aws ec2 server? or use ngrock..? which code to run and where? can you write a guide?

**Comment by thewebcapsule** [comment] 2021-05-30 13:37
Those who created their own buckets, is it working fine for you now?

**Comment by amitcodin** [comment] 2021-05-30 13:42
Its still really slow. Not yet working for me

**Comment by ggoel1998** [comment] 2021-05-30 13:43
> Those who created their own buckets, is it working fine for you now?

Terribly slow and not responsive after alot of tries

**Comment by rooniks** [comment] 2021-05-30 13:57
> Those who created their own buckets, is it working fine for you now?

Working fine for me. 

@bombardier-gif Created a pull request for using personal kvdb buckets: https://github.com/bombardier-gif/covid-vaccine-booking/pull/408

Other options:
We can deploy a simple REST service ourselves which does the same job like kvdb.

**Comment by thewebcapsule** [comment] 2021-05-30 14:00
> > Those who created their own buckets, is it working fine for you now?
> 
> Working fine for me.
> 
> @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> 
> Other options:
> We can deploy a simple REST service ourselves which does the same job like kvdb.

Which line of code did you change for the app?

**Comment by rooniks** [comment] 2021-05-30 14:06
> > > Those who created their own buckets, is it working fine for you now?
> > 
> > 
> > Working fine for me.
> > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > Other options:
> > We can deploy a simple REST service ourselves which does the same job like kvdb.
> 
> Which line of code did you change for the app?

None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.

**Comment by thewebcapsule** [comment] 2021-05-30 14:18
> > > > Those who created their own buckets, is it working fine for you now?
> > > 
> > > 
> > > Working fine for me.
> > > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > > Other options:
> > > We can deploy a simple REST service ourselves which does the same job like kvdb.
> > 
> > 
> > Which line of code did you change for the app?
> 
> None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.

I edited utils.py on my side and changed the bucket key but it tells me OTP len 0. Changed the key in the app as well. What am I doing wrong?

**Comment by rooniks** [comment] 2021-05-30 14:21
> > > > > Those who created their own buckets, is it working fine for you now?
> > > > 
> > > > 
> > > > Working fine for me.
> > > > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > > > Other options:
> > > > We can deploy a simple REST service ourselves which does the same job like kvdb.
> > > 
> > > 
> > > Which line of code did you change for the app?
> > 
> > 
> > None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.
> 
> Nevermind, works now.

Yeah, if you're using IFTTT app, it will work. For people using Cowin OTP Retriever app bundled with this project, it won't work until that app is updated.

**Comment by pics12456** [comment] 2021-05-30 14:22
Can it be done for Shortcuts app - Iphone?

**Comment by rooniks** [comment] 2021-05-30 14:26
> Can it be done for Shortcuts app - Iphone?

It will work on Shortcuts too. You'll just need to update the URL in the app to reflect your personal KVDB bucket and use the same in the script.

Refer: https://github.com/rooniks/covid-vaccine-booking/tree/personal_kvdb_bucket#kvdb-setup
and https://github.com/rooniks/covid-vaccine-booking/tree/personal_kvdb_bucket#setup-guide-for-ios

**Comment by Nikhil-Gohil** [comment] 2021-05-30 14:35
> 
> 
> > > > > > Those who created their own buckets, is it working fine for you now?
> > > > > 
> > > > > 
> > > > > Working fine for me.
> > > > > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > > > > Other options:
> > > > > We can deploy a simple REST service ourselves which does the same job like kvdb.
> > > > 
> > > > 
> > > > Which line of code did you change for the app?
> > > 
> > > 
> > > None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.
> > 
> > 
> > Nevermind, works now.
> 
> Yeah, if you're using IFTTT app, it will work. For people using Cowin OTP Retriever app bundled with this project, it won't work until that app is updated.

Why not? Thee app already has a way to update the kvdb bucket, just update it and it should work. Woked fine for me, however it is a little slow.

**Comment by rooniks** [comment] 2021-05-30 14:36
> > > > > > > Those who created their own buckets, is it working fine for you now?
> > > > > > 
> > > > > > 
> > > > > > Working fine for me.
> > > > > > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > > > > > Other options:
> > > > > > We can deploy a simple REST service ourselves which does the same job like kvdb.
> > > > > 
> > > > > 
> > > > > Which line of code did you change for the app?
> > > > 
> > > > 
> > > > None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.
> > > 
> > > 
> > > Nevermind, works now.
> > 
> > 
> > Yeah, if you're using IFTTT app, it will work. For people using Cowin OTP Retriever app bundled with this project, it won't work until that app is updated.
> 
> Why not? The app already has a way to update the kvdb bucket, just update it and it should work. Worked fine for me, however it is a little slow, not sure if it's because kvdb is being hit hard or some other reason.

Oh yes. My bad. I saw the bucket value hardcoded in strings.xml and assumed that it was being statically used.

**Comment by pics12456** [comment] 2021-05-30 15:03
> > > > > > > Those who created their own buckets, is it working fine for you now?
> > > > > > 
> > > > > > 
> > > > > > Working fine for me.
> > > > > > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > > > > > Other options:
> > > > > > We can deploy a simple REST service ourselves which does the same job like kvdb.
> > > > > 
> > > > > 
> > > > > Which line of code did you change for the app?
> > > > 
> > > > 
> > > > None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.
> > > 
> > > 
> > > Nevermind, works now.
> > 
> > 
> > Yeah, if you're using IFTTT app, it will work. For people using Cowin OTP Retriever app bundled with this project, it won't work until that app is updated.
> 
> Why not? The app already has a way to update the kvdb bucket, just update it and it should work. Worked fine for me, however it is a little slow, not sure if it's because kvdb is being hit hard or some other reason.

Does this work for windows exe app as well?
covid-vaccine-slot-booking.exe - I am using this
Just like all oher options we select, can we also specify the bucket id?

**Comment by darthfishious** [comment] 2021-05-30 15:10
> > > > > Those who created their own buckets, is it working fine for you now?
> > > > 
> > > > 
> > > > Working fine for me.
> > > > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > > > Other options:
> > > > We can deploy a simple REST service ourselves which does the same job like kvdb.
> > > 
> > > 
> > > Which line of code did you change for the app?
> > 
> > 
> > None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.
> 
> Nevermind, works now.

Is the original bucket also working now or just the new buckets?

**Comment by tilakv95** [comment] 2021-05-30 15:16
> > > > > > Those who created their own buckets, is it working fine for you now?
> > > > > 
> > > > > 
> > > > > Working fine for me.
> > > > > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > > > > Other options:
> > > > > We can deploy a simple REST service ourselves which does the same job like kvdb.
> > > > 
> > > > 
> > > > Which line of code did you change for the app?
> > > 
> > > 
> > > None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.
> > 
> > 
> > Nevermind, works now.
> 
> Is the original bucket also working now or just the new buckets?

Only the new buckets

**Comment by rooniks** [comment] 2021-05-30 15:17
> > > > > > > Those who created their own buckets, is it working fine for you now?
> > > > > > 
> > > > > > 
> > > > > > Working fine for me.
> > > > > > @bombardier-gif Created a pull request for using personal kvdb buckets: #408
> > > > > > Other options:
> > > > > > We can deploy a simple REST service ourselves which does the same job like kvdb.
> > > > > 
> > > > > 
> > > > > Which line of code did you change for the app?
> > > > 
> > > > 
> > > > None. It would involve UI changes in the app to get the bucket key from the user via a text box. I'm not an Android developer. Expecting someone else to do it.
> > > 
> > > 
> > > Nevermind, works now.
> > 
> > 
> > Is the original bucket also working now or just the new buckets?
> 
> Only the new buckets

Yeah. The original one expired. Once this pull request gets merged, things should be fine again: https://github.com/bombardier-gif/covid-vaccine-booking/pull/408

**Comment by nijeesh4all** [comment] 2021-05-30 15:32
>@nijeesh4all can you elaborate how to setup aws ec2 server? or use ngrock..? which code to run and where? can you write a guide?


sorry @toshthakkar , i was AFK.

i will explain how to setup it up to run on AWS. I havn't tried the hosting it on on local machine, but as i mentioned there are a few side-effect that you have to take care of when running in local. 


this is how i set it up in AWS. 

Step 1: 

( You will need an AWS account for this , this can be done on other cloud computing services as well  )

[AWS free tire](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all)

step 2: 

Launch an linux EC2 instance and SSH into it.
https://medium.com/@jameshamann/setting-up-an-ubuntu-ec2-instance-from-scratch-78a166167a22

Ubuntu works great i have some trouble setting it up on amazon Linux ( which is a version of centOS ).

step 4: 
Edit the firewall inbound rules for the instance you just created 


https://www.youtube.com/watch?v=59W5ZHPbwgo

add  to port `8000` as `TCP` rule with `0.0.0.0/0` as destination there. 

Step 5: 

follow the steps in the documentation here install the python script. 
https://github.com/bombardier-gif/covid-vaccine-booking

step 6: 
get your instance's public ip ( the ip/address which you used to ssh into the server )


step 7: 
add the python script and run it in the background 
```

touch server.py
vi server.py 
```

copy and paste all of this to the file 

```
from http.server import HTTPServer, BaseHTTPRequestHandler

from io import BytesIO

class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    message = ''

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(SimpleHTTPRequestHandler.message.encode())

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length).decode('utf-8')
        self.send_response(200)
        self.end_headers()
        response = BytesIO()
        SimpleHTTPRequestHandler.message = body
        self.wfile.write(SimpleHTTPRequestHandler.message.encode())


httpd = HTTPServer(('localhost', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()
```

then run the process in the background with 

i use screen to run it the background

```
screen
python3 server.py
```

then press `ctrl+a` the `ctrl+d` to detach the process so it will continue running in the background.

step 8:

edit the code to make it work with your custom server 

got to `src/utils.py` the change the line 1042 

from 
```
storage_url = "https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/" + mobile
```

to 

```
storage_url =  "http://<your server public url>:8080"
```

and 

got to `src/utils.py` the change the line 1013

from 
```
response = requests.put(storage_url, data={})
```

to 

```
response = requests.post(storage_url+'/message', data="", headers={'Content-Type': 'text/plain'})
```

step 9:

configure IFFT ( cowin sms retriever wont work )

follow the steps mentioned in the readme here

just use this url instead of the url given there `http://<your server ip>:8080` 

step 10:

now run the cowin python script with this  `python3 src/covid-vaccine-slot-booking.py`

**Comment by nolimits0007** [comment] 2021-05-30 16:07
The newly created bucket is working great and the app (CoWinOtpRetreiver) also sending automated sms.

plz everybody get main code from [](https://github.com/rooniks/covid-vaccine-booking)

then plz input their bucket code after running script . PFA image

<img width="922" alt="Screenshot 2021-05-30 at 21 35 33" src="https://user-images.githubusercontent.com/84738436/120111346-36defe80-c18f-11eb-9da6-a47612a9fae1.png">



If don't want give their original email ID at [](https://kvdb.io/)  then use temporary email.

**Comment by rooniks** [comment] 2021-05-30 16:15
> The newly created bucket is working great and the app (CoWinOtpRetreiver) also sending automated sms.
> 
> plz everybody get main code from https://github.com/rooniks/covid-vaccine-booking
> 
> then plz input their bucket code after running script . PFA image
> 
> <img alt="Screenshot 2021-05-30 at 21 35 33" width="922" src="https://user-images.githubusercontent.com/84738436/120111346-36defe80-c18f-11eb-9da6-a47612a9fae1.png">
> 
> If don't want give their original email ID at https://kvdb.io/ then use temporary email.

Pull request for this issue is pending to be merged: https://github.com/bombardier-gif/covid-vaccine-booking/pull/408
Once it gets merged, it would be fixed in this repository itself.

**Comment by pics12456** [comment] 2021-05-30 16:32
Trying to use python(for the first time)
Trying to use cmd
seeing this error
![image](https://user-images.githubusercontent.com/85064995/120112223-95f24280-c192-11eb-9ed4-f80313d8dd65.png)

File path
![image](https://user-images.githubusercontent.com/85064995/120112253-b3bfa780-c192-11eb-9090-349e407a99ca.png)

Please help resolving the error

**Comment by nolimits0007** [comment] 2021-05-30 16:48
> Trying to use python(for the first time)
> Trying to use cmd
> seeing this error
> ![image](https://user-images.githubusercontent.com/85064995/120112223-95f24280-c192-11eb-9ed4-f80313d8dd65.png)
> 
> File path
> ![image](https://user-images.githubusercontent.com/85064995/120112253-b3bfa780-c192-11eb-9090-349e407a99ca.png)
> 
> Please help resolving the error

After opening cmd apply this command  pip install -r requirements.txt

then use  python src\covid-vaccine-slot-booking.py

**Comment by pics12456** [comment] 2021-05-30 17:14
Now working
Thanks @nolimits0007

**Comment by MananManek** [comment] 2021-05-30 18:05
I'm using exe file

I don't know how to use python can someone do a step by step guide for users like me?

**Comment by Bruce119-NC** [comment] 2021-05-30 18:50
https://github.com/rooniks/covid-vaccine-booking
use this repo it's working perfect.

**Comment by MananManek** [comment] 2021-05-30 19:16
> https://github.com/rooniks/covid-vaccine-booking
> use this repo it's working perfect.

I can't find an exe file in this repo to run it.... pls help @rooniks @Bruce119-NC

**Comment by nolimits0007** [comment] 2021-05-30 20:04
> > https://github.com/rooniks/covid-vaccine-booking
> > use this repo it's working perfect.
> 
> I can't find an exe file in this repo to run it.... pls help @rooniks @Bruce119-NC

First u learn from this link https://github.com/bombardier-gif/covid-vaccine-booking#quickstart-guide

Then if u have problem further than learn from this  https://github.com/bombardier-gif/covid-vaccine-booking/issues/397#issuecomment-851018802

by the way latest repo that is working is https://github.com/rooniks/covid-vaccine-booking . Download main code from here.

**Closed** 2021-06-04 17:21 UTC
Labels: duplicate
