### ISSUE TITLE
Delayed Data from API and booking is missed out most of the times 

### ISSUE THREAD

**Issue by shivaslifzz** [bombardier-gif/covid-vaccine-booking#433] opened 2021-06-01 17:12 UTC
@bombardier-gif  @6mxo89sqh
Example 1:

I am using search option 3 and I got notifactions for 500003 pincode but booking was missed 

![image](https://user-images.githubusercontent.com/61616987/120361699-c6b7b080-c327-11eb-8469-87267015a55e.png)
![image](https://user-images.githubusercontent.com/61616987/120361827-f6ff4f00-c327-11eb-9f2e-314fd3fd22d6.png)
![image](https://user-images.githubusercontent.com/61616987/120363549-e64fd880-c329-11eb-9aaf-7538666b84a6.png)

Example 2:

I am using search option 2 and I got notifactions for 500029 pincode but booking was missed again 

![image](https://user-images.githubusercontent.com/61616987/120362086-4f365100-c328-11eb-8314-6032d3083ccf.png)
![image](https://user-images.githubusercontent.com/61616987/120362222-78ef7800-c328-11eb-800f-a74cf4f123e8.png)
![image](https://user-images.githubusercontent.com/61616987/120363585-f1a30400-c329-11eb-8c4a-e635c3f8b2eb.png)

Example 3:

I am using search option 2 and I got notifactions for 500033 pincode with 150 slots but the script identified only 50 slots, luckily this time I am able to book it but I think there is 20-30 seconds plus delay in getting the real data !!!!!

![image](https://user-images.githubusercontent.com/61616987/120363992-5d856c80-c32a-11eb-87d6-b9c5d7916511.png)
![image](https://user-images.githubusercontent.com/61616987/120364031-64ac7a80-c32a-11eb-8dab-d45b23ed3376.png)

**Comment by adityap27** [comment] 2021-06-02 02:10
I also faced this same issue yesterday while booking. :(

**Comment by salian** [comment] 2021-06-02 04:00
I think it's just a matter of the 9 second interval you are using. 

Slots that open at known times are getting over in well under 9 seconds in my city. On average under 3 seconds.

So if you use a 9 second interval, it's possible the slots opened just milliseconds after your last query was made, in which case you will not be able to get the booking. If you are lucky, the slots opened just one second before your current query, in which case you get the booking.

Keeping the interval shorter will increase the probability of getting the slot. But this is subject to the constraint of getting logged out or temporarily blocked for too many API calls.

Booking strategies:

1. When slot opening time is known

If you know the exact time when slots will open down to a 100 second interval, you can assuredly get the slot with high confidence by keeping the interval as 1 second. If the slots don't open during the first 95 seconds (keeping few calls for making the actual booking), you will be blocked from making requests until the next 4 minutes. If a slot opens in those 4 minutes when you are blocked, oops. So this strategy works if you know the time slots are expected to open, from previous trends, accurately within a ~1.5 minute interval.

2. When slots open randomly

If slots open randomly you can keep trying at 5 second intervals, this is enough to not trip the current rate limit. Others can still book slots before you if their api request was made between the slots opening and your request. It's a probability game. But the probability of others trying reduces at random hours. So this strategy works better if you try it on at odd hours when the masses are not expecting slots to open, like between 1 am to 7 am etc.

**Comment by shivaslifzz** [comment] 2021-06-02 04:10
> I think it's just a matter of the 9 second interval you are using.
> 
> Slots that open at known times are getting over in well under 9 seconds in my city. On average under 3 seconds.
> 
> So if you use a 9 second interval, it's possible the slots opened just milliseconds after your last query was made, in which case you will not be able to get the booking. If you are lucky, the slots opened just one second before your current query, in which case you get the booking.
> 
> Keeping the interval shorter will increase the probability of getting the slot. But this is subject to the constraint of getting logged out or temporarily blocked for too many API calls.
> 
> Booking strategies:
> 
> 1. When slot opening time is known
> 
> If you know the exact time when slots will open down to a 100 second interval, you can assuredly get the slot with high confidence by keeping the interval as 1 second. If the slots don't open during the first 95 seconds (keeping few calls for making the actual booking), you will be blocked from making requests until the next 4 minutes. If a slot opens in those 4 minutes when you are blocked, oops. So this strategy works if you know the time slots are expected to open, from previous trends, accurately within a ~1.5 minute interval.
> 
> 1. When slots open randomly
> 
> If slots open randomly you can keep trying at 5 second intervals, this is enough to not trip the current rate limit. Others can still book slots before you if their api request was made between the slots opening and your request. It's a probability game. But the probability of others trying reduces at random hours. So this strategy works better if you try it on at odd hours when the masses are not expecting slots to open, like between 1 am to 7 am etc. There are some cancellations that happen which cause one slot to become available. This strategy is for single person bookings.

Bro here problem is not about the reefresh rate because I already changed the logic for immediate refresh but there is no luck because of the delay of the data, FYI please look at the first example the slots opened at 22:01 but our code is not able to pick at 22:01:56, 22:02:06 and at 22:02:15 it's saying that slots are booked this is showing that refresh from API's are delayed

**Comment by adityap27** [comment] 2021-06-02 04:21
@salian , the issue is not booking strategy. 
Main issue is that this script is getting data 10-20 delayed than the telegram bots.

**Comment by shailesh** [comment] 2021-06-02 06:53
I can see a gap of 9 seconds in the above screenshot shared. and due to which the slots have gone fully bked. so no delayed response. we do not have any async method here

**Comment by adityap27** [comment] 2021-06-02 06:57
Seems like this issue #397 , where he was having issues with option3 and he solved using ascending order of pincodes with option3

**Comment by shivaslifzz** [comment] 2021-06-02 06:59
> I can see a gap of 9 seconds in the above screenshot shared. and due to which the slots have gone fully bked. so no delayed response. we do not have any async method here

bro see the example and comment example 1 the script is delayed by 20 -30 seconds than the telegram bots

**Comment by shailesh** [comment] 2021-06-02 07:03
I can see 9 seconds gap in the script whereas seconds are invisible in telegram SMS, but seems like SMS came around 22:04 or 01. We know that this is not the best Algorithm we need to make it more robust so please be with us and help us make it better if you find some discrepancies. Thanks

**Comment by shivaslifzz** [comment] 2021-06-02 07:05
> I can see 9 seconds gap in the script whereas seconds are invisible in telegram SMS, but seems like SMS came around 22:04 or 01. We know that this is not the best Algorithm we need to make it more robust so please be with us and help us make it better if you find some discrepancies. Thanks

My observation is only the way we are pulling the data from the API is delayed apart from this code is top notch as now

**Comment by AnjunaBoy** [comment] 2021-06-03 12:23
Observed this issue for 2 days. Slots are opening and getting booked but the script doesnt catch them. Telegram alerts come immediately but the script does not see the slots for atleast 30-40 seconds, sometimes longer. Saw this with atleast 5 centres.

**Comment by evioxtech** [comment] 2021-06-04 13:18
Yes strangely I tried to run on aws ec2 ubuntu instance as well but still slots were being missed. May 28 build was working like a charm

**Comment by bombardier-gif** [comment] 2021-06-04 17:25
I am closing this ticket for managing new tickets well. Please continue your conversation

**Closed by bombardier-gif** 2021-06-04 17:25 UTC
