### ISSUE TITLE
Script not able to pick the available slots - NO BOOKING ATTEMPT

### ISSUE THREAD

**Issue by siddharthgoyal90** [bombardier-gif/covid-vaccine-booking#397] opened 2021-05-29 03:36 UTC
@bombardier-gif The latest code main branch is not attempting booking even when slots are open. It just continues to say no options viable…. This is something I am getting from last 2 days now. Any thoughts please? Quite urgent.

**Comment by apoorvakasbekar** [comment] 2021-05-29 05:08
@siddharthgoyal90  I am facing the exact same issue.

**Comment by Nakul93** [comment] 2021-05-29 05:51
Are you guys able to see the available centres?

**Comment by siddharthgoyal90** [comment] 2021-05-29 06:04
Yes @Nakul93 It opened once again 30 minutes back. But no luck with the script. Running in same state saying No Viable Options.

**Comment by Nakul93** [comment] 2021-05-29 06:40
Make sure you have selected the right options and confirm that the same is available on cowin portal

**Comment by siddharthgoyal90** [comment] 2021-05-29 07:02
@Nakul93 Cross verified multiple times by selecting right options on script inputs with the corresponding same ones on CoWIN. I was able to book multiple times before 2 days, but since last 2 days (i.e., post using the latest code on main branch) - the booking attempt is not coming through.

See the below screenshot for reference - this is non-stop continuing with the same inspite of the fact that slots were available/ open on CoWIN. Any thoughts?
![image](https://user-images.githubusercontent.com/84772298/120061236-e033d080-c079-11eb-90e6-34cbce4aec63.png)

**Comment by Nakul93** [comment] 2021-05-29 07:24
Could you try using pincode instead of district

**Comment by siddharthgoyal90** [comment] 2021-05-29 07:57
@Nakul93 I have chose Option 3 - state with pincodes from optimization standpoint only. Is there any other way of using pincodes you are proposing/ recommending?

**Comment by Nakul93** [comment] 2021-05-29 08:00
Choose option 1, which is only for pincode and check if that works.

**Comment by ernitish** [comment] 2021-05-29 09:02
Last night at 9.30 i have booked slots with option 1.

**Comment by siddharthgoyal90** [comment] 2021-05-29 10:09
@ernitish @Nakul93  Are we saying that the latest main branch works with Option 1 as of now?
I’ve initiated the script with Option 1 - let’s see if it works.

**Comment by siddharthgoyal90** [comment] 2021-05-29 13:40
@Nakul93 Following are the observations:

- I was able to book the appointment with Option #1 finally.
- It seems Option #2 and Option #3 doesn't work for any inputs.
- Option #1 work only when there are sudden 1-2 slots available BUT not when slots are scheduled to open for any center at a particular time of the day.

Thoughts?

**Comment by Nakul93** [comment] 2021-05-29 13:57
Ok not sure if the bug mentioned in #314 was completely fixed. 
As for booking the slots which are scheduled to open at a particular time, the centres show after some delay (for me it was 15-30secs). Maybe this due to caching as mentioned in the api documentation
A trick that might work is to wait for the exact time or wait for the telegram notification before you start searching centres. Also make sure that you haven't logged into the portal via app/web

**Comment by nolimits0007** [comment] 2021-05-30 03:39
here the problem is this if we select option 3 , I my case i selected 33 then 3 and then 500004,500033,500034,500038
It does not showing any centers available. I tried for 45+

**Comment by nolimits0007** [comment] 2021-05-30 03:55
Option 3 with 4 pin codes not showing any centers very difficult to book . 

<img width="1032" alt="Screenshot 2021-05-30 at 09 22 45" src="https://user-images.githubusercontent.com/84738436/120091464-fd73a800-c128-11eb-94a7-9adcd3cbe846.png">

**Comment by nolimits0007** [comment] 2021-05-30 07:05
Option 3 working perfectly. i selected 5 centers .Booking confirmed.

<img width="914" alt="Screenshot 2021-05-30 at 12 04 32" src="https://user-images.githubusercontent.com/84738436/120095404-7a138000-c143-11eb-9b18-a63cd2472478.png">

**Comment by pics12456** [comment] 2021-05-30 13:09
Nothing works
tried option 2 - slots open, doesn't work
then option 3 with 5 pincodes, again no
then option 1 with 5 pincodes, again no

**Comment by Nakul93** [comment] 2021-05-30 13:26
Try with 3 pincodes or less

**Comment by pics12456** [comment] 2021-05-30 13:27
Acha will start with it now

**Comment by nolimits0007** [comment] 2021-05-30 13:43
I Have booked with option 3 and 4 picodes frequency 7.
@pics12456 plz attach some screenshots.

<img width="1590" alt="Screenshot 2021-05-30 at 18 37 24" src="https://user-images.githubusercontent.com/84738436/120106551-07be9200-c17b-11eb-91fe-8512b0c211e8.png">

**Comment by pics12456** [comment] 2021-05-30 13:51
@nolimits0007 

I had not taken the screenshot then
But I can explain the scenario

3 - Hyderabad
Pin codes: 500003,500004,500082,500004,500033
Frequency :7
I also tried with 10 frequency earlier in the afternoon

The slot AIMSR (Pin:500033) opened at 6:03PM
But the script was showing no viable options and continued as normal

I am also entering manual otp so constantly sitting near the system 

Please help

**Comment by pics12456** [comment] 2021-05-30 13:53
At the moment I have changed it 
to option 1
with just 3 pincodes
500003,500004,500082
frequency :10 since 7 is getting blocked by Cowin

![image](https://user-images.githubusercontent.com/85064995/120106908-7f40f100-c17c-11eb-91b6-54f97302dc0b.png)

**Comment by rodeoz** [comment] 2021-05-30 14:18
Was able to book successfully yesterday. Used Option 1 (for pin code only) and chose 2 pin codes with a refresh frequency of 10 seconds. 

It missed the slot when I chose Option 3 (district and then sort by pin code).

**Comment by nolimits0007** [comment] 2021-05-30 14:40
> @nolimits0007
> 
> I had not taken the screenshot then
> But I can explain the scenario
> 
> 3 - Hyderabad
> Pin codes: 500003,500004,500082,500004,500033
> Frequency :7
> I also tried with 10 frequency earlier in the afternoon
> 
> The slot AIMSR (Pin:500033) opened at 6:03PM
> But the script was showing no viable options and continued as normal
> 
> I am also entering manual otp so constantly sitting near the system
> 
> Please help

@pics12456  Try this Trick.
Use option 3. Type 33 then 3 when it comes to pincode use them in ascending order as mentioned below use frequency 7 it will pick slot definitely and something goes wrong take screenshot. 
500003,500004,500004,500033,500082

**Comment by Nakul93** [comment] 2021-05-30 14:44
My observation is there is always some delay between the slots actually opening up and the script showing those slots. I’ve tried with 1 pincode and still the slots started showing up for me after roughly 30secs after the actual time. Even the telegram bot alerted at the exact time, but the script has some delay. Not sure if has to do with the caching of data as mentioned in the API documentation

**Comment by pics12456** [comment] 2021-05-30 14:47
So is their way out?

**Comment by nolimits0007** [comment] 2021-05-30 14:47
> My observation is there is always some delay between the slots actually opening up and the script showing those slots. I’ve tried with 1 pincode and still the slots started showing up for me after roughly 30secs after the actual time. Even the telegram bot alerted at the exact time, but the script has some delay. Not sure if has to do with the caching of data as mentioned in the API documentation

In this case i think again download complete from the main code remove the use folder and use new one. Because in Hyderabad i have  done booking 2 times today .

**Comment by nolimits0007** [comment] 2021-05-30 14:48
> So is their way out?

what i replied u can do that way.

**Comment by pics12456** [comment] 2021-05-30 14:50
Yeah. I have set it up with that manner -option 3
pincodes in ascending order

Hope I get the slot

**Comment by Nakul93** [comment] 2021-05-30 14:53
> > My observation is there is always some delay between the slots actually opening up and the script showing those slots. I’ve tried with 1 pincode and still the slots started showing up for me after roughly 30secs after the actual time. Even the telegram bot alerted at the exact time, but the script has some delay. Not sure if has to do with the caching of data as mentioned in the API documentation
> 
> In this case i think again download complete from the main code remove the use folder and use new one. Because in Hyderabad i have done booking 2 times today .

I have had the updated code. I think what you are suggesting is to delete the pycache folder, it won’t really help.
The reason you were probably able to book was maybe due to less traffic. There are always a lot of traffic (especially in major cities)when centers have specific slot opening times.

**Comment by pics12456** [comment] 2021-05-30 15:16
It tried booking
And i saw this error
![image](https://user-images.githubusercontent.com/85064995/120109641-efa13f80-c187-11eb-8cb8-f3bf5bf58b18.png)

![image](https://user-images.githubusercontent.com/85064995/120109671-0778c380-c188-11eb-9d1c-f38f56d77e28.png)

**Comment by Nakul93** [comment] 2021-05-30 15:20
@pics12456 Pls add this file in your main directory 
https://github.com/bombardier-gif/covid-vaccine-booking/blob/main/src/model.txt

**Comment by pics12456** [comment] 2021-05-30 15:24
Done
![image](https://user-images.githubusercontent.com/85064995/120109926-2592f380-c189-11eb-859b-cba3583a96f1.png)

Please let me know if this is correct

**Comment by pics12456** [comment] 2021-05-30 15:24
![Untitled](https://user-images.githubusercontent.com/85064995/120109949-40fdfe80-c189-11eb-9348-e964fbe00157.png)

**Comment by Nakul93** [comment] 2021-05-30 15:26
> Done
> ![image](https://user-images.githubusercontent.com/85064995/120109926-2592f380-c189-11eb-859b-cba3583a96f1.png)
> 
> Please let me know if this is correct

This should be fine.

**Comment by pics12456** [comment] 2021-05-30 15:28
Thanks

**Comment by nolimits0007** [comment] 2021-05-30 15:38
> It tried booking
> And i saw this error
> ![image](https://user-images.githubusercontent.com/85064995/120109641-efa13f80-c187-11eb-8cb8-f3bf5bf58b18.png)
> 
> ![image](https://user-images.githubusercontent.com/85064995/120109671-0778c380-c188-11eb-9d1c-f38f56d77e28.png)

Earlier u were not getting slots at least u r getting slots now.

what my opinion is that u download main code from site extract it on desktop.

the folder extracted . go to tests folder extract windows exe and the go to windows exe folder.

There run captcha_tests.exe file if u see something like this.

<img width="891" alt="Screenshot 2021-05-30 at 21 04 05" src="https://user-images.githubusercontent.com/84738436/120110394-dc43a380-c18a-11eb-95a1-62a0d2b29017.png">

After pressing quit u should see something like this then it will work.

<img width="917" alt="Screenshot 2021-05-30 at 21 04 40" src="https://user-images.githubusercontent.com/84738436/120110412-f54c5480-c18a-11eb-865e-c3f08786454c.png">

plz do this u will get slot.  Happy Vaccination !!!

**Comment by pics12456** [comment] 2021-05-31 02:24
a.I have done the captcha test
![image](https://user-images.githubusercontent.com/85064995/120131096-3ffaba80-c1e5-11eb-8784-ffe4082d1001.png)

b. Yet while it was trying to book today morning, its showing this error
![image](https://user-images.githubusercontent.com/85064995/120131164-6ddfff00-c1e5-11eb-99b2-7c694cdab3f6.png)

Working using cmd

**Comment by pics12456** [comment] 2021-05-31 02:39
Just booked 3 slots now
Thanks for the help @nolimits0007 @Nakul93 and ofcourse @bombardier-gif 
![image](https://user-images.githubusercontent.com/85064995/120132163-776a6680-c1e7-11eb-99fb-5a2c37f90aae.png)

**Comment by rishirawal** [comment] 2021-05-31 03:48
Did you use option 2 or 3

**Comment by pics12456** [comment] 2021-05-31 05:28
Option 3
Pincodes in ascending manner

**Comment by nolimits0007** [comment] 2021-05-31 07:29
> Just booked 3 slots now
> Thanks for the help @nolimits0007 @Nakul93 and of course @bombardier-gif
> ![image](https://user-images.githubusercontent.com/85064995/120132163-776a6680-c1e7-11eb-99fb-5a2c37f90aae.png)

I told u that u will do. Try again & again till u succeed . Happy Vaccination !!!

plz help others .

**Comment by manasisadekar** [comment] 2021-05-31 16:27
Can anyone confirm which option to use for 2nd Dose at Pune location ? I tried for 1st option 2 and it worked for me, but for 2nd Dose I need confirmation before opening slot for Pune, if option 2 worked for pune.. does it mean that for 2nd dose also it will work ? also anyone tried 2 people at same time ?

**Comment by adityap27** [comment] 2021-06-02 04:32
> Option 3
> Pincodes in ascending manner

Any **reason** why to use ascending  pincodes ?

I used option 3 with **unsorted** pincodes and was **not able to book** even when telegram bot showed notifications and slots were availabe for like 20-30 seconds...

**Comment by BumpyKnuckls** [comment] 2021-06-03 16:33
Marking this as closed to better track open issues. Please feel free to continue the discussion and consider reopening the issue if required

**Closed by BumpyKnuckls** 2021-06-03 16:33 UTC
