### ISSUE TITLE
Private KVDB bucket asked for manual OTP entry as well

### ISSUE THREAD

**Issue by mrms123** [bombardier-gif/covid-vaccine-booking#456] opened 2021-06-04 07:42 UTC
Private KVDB bucket asked for manual OTP entry as well

**Comment by 520rahul** [comment] 2021-06-04 08:47
+1

**Comment by 6mxo89sqh** [comment] 2021-06-04 10:00
Duplicate of #441 . it  is fixed but not released yet. It will be released soon.

**Closed by 6mxo89sqh** 2021-06-04 10:00 UTC
